# Generated by Django 2.2.1 on 2019-05-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'awards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BannedDomains',
            fields=[
                ('domain', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'exile_nexus.banned_domains',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LogLogins',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('username', models.TextField(blank=True, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('address', models.GenericIPAddressField(blank=True, null=True)),
                ('forwarded_address', models.TextField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=128, null=True)),
                ('success', models.BooleanField()),
            ],
            options={
                'db_table': 'exile_nexus.log_logins',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128, unique=True)),
                ('xml', models.TextField()),
            ],
            options={
                'db_table': 'news',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NexusUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('lcid', models.IntegerField()),
                ('registered', models.DateTimeField()),
                ('registration_ip', models.GenericIPAddressField()),
                ('last_visit', models.DateTimeField()),
                ('last_universeid', models.IntegerField(blank=True, null=True)),
                ('privilege_see_hidden_universes', models.BooleanField()),
                ('ad_code', models.TextField(blank=True, null=True)),
                ('ad_last_display', models.DateTimeField()),
                ('cheat_detected', models.DateTimeField(blank=True, null=True)),
                ('mail_sent', models.BooleanField()),
            ],
            options={
                'db_table': 'nexus_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Universes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('visible', models.BooleanField()),
                ('login_enabled', models.BooleanField()),
                ('players_limit', models.IntegerField()),
                ('registration_until', models.DateTimeField(blank=True, null=True)),
                ('ranking_enabled', models.BooleanField()),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('has_fastconnect', models.BooleanField()),
            ],
            options={
                'db_table': 'universes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersSuccesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('success_id', models.IntegerField()),
                ('universe_id', models.IntegerField()),
                ('added', models.DateTimeField()),
            ],
            options={
                'db_table': 'users_successes',
                'managed': True,
            },
        ),
    ]
